#!/usr/bin/env bash
# Installs Nginx with some configurations
# where it should be listening on port 80
# a page that will return a Hello World string
#

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \ sudo apt-get install nginx -y

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Creating new index
echo "Hello World!" | sudo tee /var/www/html/index.html

# Restarting nginx
sudo service nginx start
