#!/usr/bin/env bash
# Installs Nginx with some configurations
# where it should be listening on port 80
# a page that will return a Hello World string
#

# Updating and installing Nginx.
sudo apt-get update
sudo apt-get install nginx

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Creating new index
echo "Hello World!" | sudo tee /var/www/html/index.html

# test nginx configurations for syntax errors
sudo nginx -t

# Restarting nginx
sudo service nginx start
