#!/usr/bin/env bash
# configures a new ubuntu machine
# Nginx where it should be listening on port 80
# a ppage that would return a Hello World string

echo -e "updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	sudo apt-get install nginx -y

echo -e "\nSetting up minor staff.\n"

#starting nginx
sudo service nginx start

#allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

#Give the user ownership to website files 
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# backup default index
c /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.backp

#creating new index
echo -e "Hello World!" > /var/www/html/index.html

# Restarting nginx
sudo service nginx restart

echo -e "\nCompleted.\n"
