#!/usr/bin/env bash
# configures  server to listening on port 80 of all servers
active IPv4IPs

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/
sites-enabled/default
sudo service nginx restart
