#!/usr/bin/env bash
# SSH client configuration

Host *
	PasswordAuthentication no
	IdentifyFile ~/.ssh/school
	SendEnv LANG LC_*
	HashKnownHosts yes
	GSSAPIAunthentication yes
	GSSAPIDelegateCredentials no
